import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

async function main() {
  const properties = [
    {
      name: 'Clairemont 4-Plex',
      neighborhood: 'Clairemont',
      address: '4215 Clairemont Dr, San Diego, CA 92117',
      units: 4,
      askingPrice: 1_250_000,
      monthlyGrossRent: 7_200,
      vacancyRate: 0.05,
      operatingExpenseRatio: 0.28,
      annualRentGrowth: 0.04,
      annualExpenseGrowth: 0.03,
      exitCapRate: 0.055,
      notes: 'Well-maintained 1970s fourplex. 2/1 units. Soft-market rents with upside.',
    },
    {
      name: 'North Park 6-Unit',
      neighborhood: 'North Park',
      address: '3822 30th St, San Diego, CA 92104',
      units: 6,
      askingPrice: 2_100_000,
      monthlyGrossRent: 11_400,
      vacancyRate: 0.04,
      operatingExpenseRatio: 0.25,
      annualRentGrowth: 0.05,
      annualExpenseGrowth: 0.03,
      exitCapRate: 0.05,
      notes: 'Craftsman-style 6-unit in walkable corridor. Mix of studio and 1/1 units.',
    },
    {
      name: 'University Heights 5-Unit',
      neighborhood: 'University Heights',
      address: '4601 Park Blvd, San Diego, CA 92116',
      units: 5,
      askingPrice: 1_750_000,
      monthlyGrossRent: 9_500,
      vacancyRate: 0.05,
      operatingExpenseRatio: 0.27,
      annualRentGrowth: 0.045,
      annualExpenseGrowth: 0.03,
      exitCapRate: 0.052,
      notes: 'Vintage 5-unit near Adams Ave retail. Strong rental demand.',
    },
    {
      name: 'Normal Heights 4-Unit',
      neighborhood: 'Normal Heights',
      address: '3245 Adams Ave, San Diego, CA 92116',
      units: 4,
      askingPrice: 1_100_000,
      monthlyGrossRent: 6_400,
      vacancyRate: 0.06,
      operatingExpenseRatio: 0.30,
      annualRentGrowth: 0.04,
      annualExpenseGrowth: 0.03,
      exitCapRate: 0.057,
      notes: 'Value-add opportunity. Deferred maintenance. Rents below market.',
    },
    {
      name: 'City Heights 8-Unit',
      neighborhood: 'City Heights',
      address: '4045 Fairmount Ave, San Diego, CA 92105',
      units: 8,
      askingPrice: 2_600_000,
      monthlyGrossRent: 14_400,
      vacancyRate: 0.07,
      operatingExpenseRatio: 0.32,
      annualRentGrowth: 0.035,
      annualExpenseGrowth: 0.03,
      exitCapRate: 0.06,
      notes: 'Large lot. Below-market rents. Strong workforce housing demand.',
    },
    {
      name: 'Hillcrest 4-Unit',
      neighborhood: 'Hillcrest',
      address: '1238 Robinson Ave, San Diego, CA 92103',
      units: 4,
      askingPrice: 1_650_000,
      monthlyGrossRent: 8_800,
      vacancyRate: 0.04,
      operatingExpenseRatio: 0.24,
      annualRentGrowth: 0.05,
      annualExpenseGrowth: 0.03,
      exitCapRate: 0.048,
      notes: 'Premium Hillcrest location. Low vacancy micro-market.',
    },
    {
      name: 'Clairemont 6-Unit',
      neighborhood: 'Clairemont',
      address: '5011 Mt Alifan Dr, San Diego, CA 92111',
      units: 6,
      askingPrice: 1_900_000,
      monthlyGrossRent: 10_200,
      vacancyRate: 0.05,
      operatingExpenseRatio: 0.26,
      annualRentGrowth: 0.04,
      annualExpenseGrowth: 0.03,
      exitCapRate: 0.055,
      notes: 'Solid income property. 1980s construction. Recent roof replacement.',
    },
    {
      name: 'North Park 4-Unit',
      neighborhood: 'North Park',
      address: '3410 Utah St, San Diego, CA 92104',
      units: 4,
      askingPrice: 1_450_000,
      monthlyGrossRent: 7_600,
      vacancyRate: 0.04,
      operatingExpenseRatio: 0.26,
      annualRentGrowth: 0.05,
      annualExpenseGrowth: 0.03,
      exitCapRate: 0.05,
      notes: 'Trendy NP location near restaurants/bars. High renter demand.',
    },
    {
      name: 'University Heights 6-Unit',
      neighborhood: 'University Heights',
      address: '4720 Mississippi St, San Diego, CA 92116',
      units: 6,
      askingPrice: 2_050_000,
      monthlyGrossRent: 10_800,
      vacancyRate: 0.05,
      operatingExpenseRatio: 0.27,
      annualRentGrowth: 0.045,
      annualExpenseGrowth: 0.03,
      exitCapRate: 0.053,
      notes: 'Corner lot. Well-maintained. Consistent occupancy history.',
    },
    {
      name: 'Normal Heights 8-Unit',
      neighborhood: 'Normal Heights',
      address: '3501 Monroe Ave, San Diego, CA 92116',
      units: 8,
      askingPrice: 2_800_000,
      monthlyGrossRent: 15_200,
      vacancyRate: 0.06,
      operatingExpenseRatio: 0.28,
      annualRentGrowth: 0.04,
      annualExpenseGrowth: 0.03,
      exitCapRate: 0.055,
      notes: 'Larger asset. Mixed unit sizes. New electrical panel.',
    },
    {
      name: 'Hillcrest 6-Unit',
      neighborhood: 'Hillcrest',
      address: '542 W Washington St, San Diego, CA 92103',
      units: 6,
      askingPrice: 2_300_000,
      monthlyGrossRent: 12_600,
      vacancyRate: 0.04,
      operatingExpenseRatio: 0.24,
      annualRentGrowth: 0.05,
      annualExpenseGrowth: 0.03,
      exitCapRate: 0.048,
      notes: 'Premium Hillcrest asset. High-quality tenants. Minimal turnover.',
    },
    {
      name: 'City Heights 4-Unit',
      neighborhood: 'City Heights',
      address: '4312 Home Ave, San Diego, CA 92105',
      units: 4,
      askingPrice: 950_000,
      monthlyGrossRent: 5_600,
      vacancyRate: 0.07,
      operatingExpenseRatio: 0.31,
      annualRentGrowth: 0.035,
      annualExpenseGrowth: 0.03,
      exitCapRate: 0.062,
      notes: 'Entry-level price point. Higher yield, higher management intensity.',
    },
  ]

  for (const property of properties) {
    await prisma.property.upsert({
      where: { id: 'seed-' + property.name.toLowerCase().replace(/\s+/g, '-') },
      update: property,
      create: {
        id: 'seed-' + property.name.toLowerCase().replace(/\s+/g, '-'),
        ...property,
      },
    })
  }

  const deals = [
    {
      id: 'demo-deal-1',
      name: 'RBD Sample 6-Unit',
      neighborhood: 'North Park',
      address: '3822 30th St, San Diego, CA 92104',
      units: 6,
      purchasePrice: 2_000_000,
      monthlyGrossRent: 10_500,
      vacancyRate: 0.05,
      operatingExpenseRatio: 0.25,
      annualRentGrowth: 0.05,
      annualExpenseGrowth: 0.03,
      holdPeriodYears: 10,
      exitCapRate: 0.05,
      acquisitionClosingCosts: 40_000,
      renovationCapex: 75_000,
      equityInvested: 2_115_000,
      preferredReturnRate: 0.06,
      sponsorPromoteRate: 0.30,
    },
    {
      id: 'demo-deal-2',
      name: 'Clairemont Value-Add 4-Unit',
      neighborhood: 'Clairemont',
      address: '4215 Clairemont Dr, San Diego, CA 92117',
      units: 4,
      purchasePrice: 1_250_000,
      monthlyGrossRent: 7_200,
      vacancyRate: 0.06,
      operatingExpenseRatio: 0.28,
      annualRentGrowth: 0.04,
      annualExpenseGrowth: 0.03,
      holdPeriodYears: 10,
      exitCapRate: 0.055,
      acquisitionClosingCosts: 25_000,
      renovationCapex: 120_000,
      equityInvested: 1_395_000,
      preferredReturnRate: 0.06,
      sponsorPromoteRate: 0.30,
    },
    {
      id: 'demo-deal-3',
      name: 'Hillcrest Premium 6-Unit',
      neighborhood: 'Hillcrest',
      address: '542 W Washington St, San Diego, CA 92103',
      units: 6,
      purchasePrice: 2_300_000,
      monthlyGrossRent: 12_600,
      vacancyRate: 0.04,
      operatingExpenseRatio: 0.24,
      annualRentGrowth: 0.05,
      annualExpenseGrowth: 0.03,
      holdPeriodYears: 10,
      exitCapRate: 0.048,
      acquisitionClosingCosts: 46_000,
      renovationCapex: 50_000,
      equityInvested: 2_396_000,
      preferredReturnRate: 0.06,
      sponsorPromoteRate: 0.30,
    },
  ]

  for (const deal of deals) {
    await prisma.deal.upsert({
      where: { id: deal.id },
      update: deal,
      create: deal,
    })
  }

  console.log('Seed complete.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
